2025-05-05 18:50:06,069 INFO    Thread-14 (_run_job):924 [wandb_setup.py:_flush():68] Current SDK version is 0.19.10
2025-05-05 18:50:06,070 INFO    Thread-14 (_run_job):924 [wandb_setup.py:_flush():68] Configure stats pid to 924
2025-05-05 18:50:06,070 INFO    Thread-14 (_run_job):924 [wandb_setup.py:_flush():68] Loading settings from C:\Users\aksha\.config\wandb\settings
2025-05-05 18:50:06,070 INFO    Thread-14 (_run_job):924 [wandb_setup.py:_flush():68] Loading settings from C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\hamiltonian-nn\wandb\settings
2025-05-05 18:50:06,070 INFO    Thread-14 (_run_job):924 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-05-05 18:50:06,070 INFO    Thread-14 (_run_job):924 [wandb_init.py:setup_run_log_directory():724] Logging user logs to C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\hamiltonian-nn\wandb\run-20250505_185006-o2y9jep1\logs\debug.log
2025-05-05 18:50:06,070 INFO    Thread-14 (_run_job):924 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\hamiltonian-nn\wandb\run-20250505_185006-o2y9jep1\logs\debug-internal.log
2025-05-05 18:50:06,070 INFO    Thread-14 (_run_job):924 [wandb_init.py:init():852] calling init triggers
2025-05-05 18:50:06,071 INFO    Thread-14 (_run_job):924 [wandb_init.py:init():857] wandb.init called with sweep_config: {'decay_param': 0.0001, 'dropout': 0.2}
config: {'_wandb': {}}
2025-05-05 18:50:06,071 INFO    Thread-14 (_run_job):924 [wandb_init.py:init():893] starting backend
2025-05-05 18:50:06,286 INFO    Thread-14 (_run_job):924 [wandb_init.py:init():897] sending inform_init request
2025-05-05 18:50:06,288 INFO    Thread-14 (_run_job):924 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-05-05 18:50:06,288 INFO    Thread-14 (_run_job):924 [wandb_init.py:init():907] backend started and connected
2025-05-05 18:50:06,288 INFO    Thread-14 (_run_job):924 [wandb_run.py:_config_callback():1429] config_cb None None {'decay_param': 0.0001, 'dropout': 0.2}
2025-05-05 18:50:06,288 INFO    Thread-14 (_run_job):924 [wandb_init.py:init():1002] updated telemetry
2025-05-05 18:50:06,353 INFO    Thread-14 (_run_job):924 [wandb_init.py:init():1026] communicating run to backend with 90.0 second timeout
2025-05-05 18:50:07,130 INFO    Thread-14 (_run_job):924 [wandb_init.py:init():1101] starting run threads in backend
2025-05-05 18:50:07,136 ERROR   Thread-14 (_run_job):924 [redirect.py:_on_write():664] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-05-05 18:50:07,137 ERROR   Thread-14 (_run_job):924 [redirect.py:_on_write():664] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-05-05 18:50:07,138 ERROR   Thread-14 (_run_job):924 [redirect.py:_on_write():664] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-05-05 18:50:07,139 ERROR   Thread-14 (_run_job):924 [redirect.py:_on_write():664] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-05-05 18:50:07,140 ERROR   Thread-14 (_run_job):924 [redirect.py:_on_write():664] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-05-05 18:50:07,141 ERROR   Thread-14 (_run_job):924 [redirect.py:_on_write():664] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-05-05 18:50:07,217 INFO    Thread-14 (_run_job):924 [wandb_run.py:_console_start():2566] atexit reg
2025-05-05 18:50:07,217 INFO    Thread-14 (_run_job):924 [wandb_run.py:_redirect():2414] redirect: wrap_raw
2025-05-05 18:50:07,217 INFO    Thread-14 (_run_job):924 [wandb_run.py:_redirect():2483] Wrapping output streams.
2025-05-05 18:50:07,217 INFO    Thread-14 (_run_job):924 [wandb_run.py:_redirect():2506] Redirects installed.
2025-05-05 18:50:07,218 INFO    Thread-14 (_run_job):924 [wandb_init.py:init():1147] run started, returning control to user process
2025-05-05 18:50:07,222 ERROR   Thread-14 (_run_job):924 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-05-05 18:50:07,224 ERROR   Thread-14 (_run_job):924 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-05-05 18:50:07,225 ERROR   MainThread:924 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\agents\pyagent.py", line 219, in _run_jobs_from_queue
    thread.join()
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-05-05 18:50:07,537 INFO    MsgRouterThr:924 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-05-05 18:50:09,549 ERROR   MainThread:924 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 2487, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\aksha\OneDrive\Desktop\codes\CP\ET_Project\my_env\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
